swagger: "2.0"
info:
    title: ""
    description: The Kubernetes Federated Credential Api
    version: 0.0.1
host: 0.0.0.0:8088
consumes:
    - application/json
    - application/xml
    - application/gob
produces:
    - application/json
    - application/xml
    - application/gob
paths:
    /exchangeToken:
        post:
            tags:
                - tokenExchange
            summary: exchangeToken tokenExchange
            operationId: tokenExchange#exchangeToken
            parameters:
                - name: Authorization
                  in: header
                  description: The JWT Token from the impersonating service account
                  required: true
                  type: string
                  maxLength: 2000
                  pattern: ^Bearer [^ ]+
                - name: ExchangeTokenRequestBody
                  in: body
                  required: true
                  schema:
                    $ref: '#/definitions/TokenExchangeExchangeTokenRequestBody'
                    required:
                        - namespace
                        - serviceAccountName
            responses:
                "200":
                    description: OK response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenResponseBody'
                        required:
                            - status
                "400":
                    description: Bad Request response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenBadRequestErrorResponseBody'
                "401":
                    description: Unauthorized response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenUnauthorizedResponseBody'
                "403":
                    description: Forbidden response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenForbiddenResponseBody'
                "404":
                    description: Not Found response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenNotFoundResponseBody'
                "406":
                    description: Not Acceptable response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenNotAcceptableResponseBody'
                "415":
                    description: Unsupported Media Type response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenUnsupportedMediaTypeResponseBody'
                "429":
                    description: Too Many Requests response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenTooManyRequestsResponseBody'
                "500":
                    description: Internal Server Error response.
                    schema:
                        $ref: '#/definitions/TokenExchangeExchangeTokenInternalErrorResponseBody'
            schemes:
                - http
            security:
                - jwt_header_Authorization: []
definitions:
    StatusResponseBody:
        title: StatusResponseBody
        type: object
        properties:
            token:
                type: string
                description: The status token
                example: 5cd
                pattern: ^(?:[A-Za-z0-9+/]{4})*(?:[A-Za-z0-9+/]{2}==|[A-Za-z0-9+/]{3}=)?$
                maxLength: 2000
        description: Status with a token.
        example:
            token: nwm
        required:
            - token
    TokenExchangeExchangeTokenBadRequestErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Bad Request (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenForbiddenResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Forbidden (default view)
        example:
            fault: false
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenInternalErrorResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Internal Server Error (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenNotAcceptableResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: true
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Not Acceptable (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenNotFoundResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Not Found (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenRequestBody:
        title: TokenExchangeExchangeTokenRequestBody
        type: object
        properties:
            namespace:
                type: string
                description: The target namespace for impersonation
                example: 9q8
                pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                maxLength: 253
            serviceAccountName:
                type: string
                description: The target serviceAccount
                example: efe
                pattern: '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*'
                maxLength: 253
        example:
            namespace: an7
            serviceAccountName: if9
        required:
            - namespace
            - serviceAccountName
    TokenExchangeExchangeTokenResponseBody:
        title: TokenExchangeExchangeTokenResponseBody
        type: object
        properties:
            status:
                $ref: '#/definitions/StatusResponseBody'
        example:
            status:
                token: aa6
        required:
            - status
    TokenExchangeExchangeTokenTooManyRequestsResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: true
        description: Too Many Requests (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: true
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenUnauthorizedResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: true
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unauthorized (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: false
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
    TokenExchangeExchangeTokenUnsupportedMediaTypeResponseBody:
        title: 'Mediatype identifier: application/vnd.goa.error; view=default'
        type: object
        properties:
            fault:
                type: boolean
                description: Is the error a server-side fault?
                example: false
            id:
                type: string
                description: ID is a unique identifier for this particular occurrence of the problem.
                example: 123abc
            message:
                type: string
                description: Message is a human-readable explanation specific to this occurrence of the problem.
                example: parameter 'p' must be an integer
            name:
                type: string
                description: Name is the name of this class of errors.
                example: bad_request
            temporary:
                type: boolean
                description: Is the error temporary?
                example: false
            timeout:
                type: boolean
                description: Is the error a timeout?
                example: false
        description: Unsupported Media Type (default view)
        example:
            fault: true
            id: 123abc
            message: parameter 'p' must be an integer
            name: bad_request
            temporary: false
            timeout: true
        required:
            - name
            - id
            - message
            - temporary
            - timeout
            - fault
securityDefinitions:
    jwt_header_Authorization:
        type: apiKey
        description: Use JWT to authenticate requests.
        name: Authorization
        in: header
